---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-webapp
  labels:
    app: vault-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault-webapp
  template:
    metadata:
      labels:
        app: vault-webapp
    spec:
      serviceAccountName: vault
      containers:
      - name: app
        image: burtlo/exampleapp-ruby:k8s
        imagePullPolicy: Always
        env:
        - name: VAULT_ADDR
          value: "http://vault:8200"
        - name: JWT_PATH
          value: "/var/run/secrets/kubernetes.io/serviceaccount/token"
        - name: SERVICE_PORT
          value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: vault-webapp-service
  namespace: default
spec:
  ports:
  - name: http
    nodePort: 30808
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: vault-webapp
  type: NodePort

