apiVersion: v1
kind: Service
metadata:
  name: vault-service
  namespace: default
spec:
  ports:
  - name: http
    nodePort: 30333
    port: 8200
    protocol: TCP
    targetPort: 8200
  selector:
    app.kubernetes.io/name: vault
  type: NodePort

