FROM grafana/grafana:7.0.6-ubuntu
MAINTAINER Adrian Eka Sanjaya

USER root

RUN apt-get update
RUN apt-get install -y sudo
RUN apt-get install -y postgresql-12 postgresql-contrib
RUN apt-get install -y systemd
