apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-failure_probe
  labels:
    team: finance
    version: 1.4.5
    environment: production
  annotations:
    description: Ini adalah aplikasi yang dibuat oleh tim product
    apapun: Apapun itu....
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      livenessProbe:
        httpGet:
          path: /404
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 5
        timeoutSeconds: 1
        successThreshold: 1
        failureThreshold: 3
